name: fp_dart
description: dart + functional programming
version: 1.0.0
homepage: https://github.com/SahandAkbarzadeh/fp_dart
author: Sahandevs <sahandevs@gmail.com>

environment:
  sdk: '>=2.6.0-dev.5.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0